import Anthropic from "@anthropic-ai/sdk";
import { type Effort } from "./pipeline/models";
import { type Usage, type UsageSink } from "./spend/pricing";

// Client factory. Key resolution: explicit per-run key (BYOK seam) → server env.
// AI Gateway swap point: to route spend through Vercel AI Gateway, set baseURL +
// the gateway key here once the web_search passthrough is verified (PLAN §12).
export function getClient(apiKey?: string): Anthropic {
  const key = apiKey || process.env.ANTHROPIC_API_KEY;
  if (!key) throw new Error("No Anthropic API key configured (set ANTHROPIC_API_KEY or pass one per run).");
  return new Anthropic({ apiKey: key });
}

// Minimal param surface we use. Cast to the SDK type at the call site so beta-ish
// fields (output_config.effort, adaptive thinking, web_search_20260209) don't
// fight version drift in the SDK's exported param types.
export interface CallParams {
  model: string;
  max_tokens: number;
  system?: string;
  messages: Anthropic.MessageParam[];
  tools?: unknown[];
  effort?: Effort;
  jsonSchema?: Record<string, unknown>; // structured output
  adaptiveThinking?: boolean;
  // Container id from a prior response's `container` field. REQUIRED on any
  // continuation of a turn whose server tools (web_search_20260209) ran in a
  // code-execution container and left a pending client tool_use — omitting it
  // makes the API reject the continuation with a 400 ("container_id is
  // required when there are pending tool uses generated by code execution").
  container?: string;
}

export interface CallOptions {
  maxPauseResumes?: number; // server-tool (web search) pause_turn resumes
  onText?: (delta: string) => void; // streamed text deltas (Stage A live feed)
  onToolNote?: (note: string) => void; // "searching the web…" etc.
  onUsage?: UsageSink; // token usage → spend ledger / kill-switch
  signal?: AbortSignal; // true request-level abort (factory cancel/timeout)
}

function buildParams(p: CallParams): Record<string, unknown> {
  const output_config: Record<string, unknown> = {};
  if (p.effort) output_config.effort = p.effort;
  if (p.jsonSchema) output_config.format = { type: "json_schema", schema: p.jsonSchema };
  const params: Record<string, unknown> = {
    model: p.model,
    max_tokens: p.max_tokens,
    messages: p.messages,
  };
  if (p.system) params.system = p.system;
  if (p.tools) params.tools = p.tools;
  if (p.container) params.container = p.container;
  if (Object.keys(output_config).length) params.output_config = output_config;
  // Sonnet 5 runs adaptive by default; Opus needs it set explicitly. Haiku 4.5
  // does not support adaptive thinking, so callers omit it.
  if (p.adaptiveThinking) params.thinking = { type: "adaptive" };
  return params;
}

// One streamed call, resuming server-tool pauses, returning the final Message.
async function streamOnce(
  client: Anthropic,
  params: Record<string, unknown>,
  opts: CallOptions,
): Promise<Anthropic.Message> {
  const stream = client.messages.stream(
    params as unknown as Anthropic.MessageStreamParams,
    opts.signal ? { signal: opts.signal } : undefined,
  );
  // Harvest the code-execution container id from RAW wire events. The SDK's
  // stream accumulator seeds its snapshot from message_start but drops every
  // message_delta field except stop_reason/stop_details/usage — so a container
  // id delivered mid-turn (when server-side code execution spins up, e.g.
  // web_search_20260209 dynamic filtering) never reaches finalMessage().
  // Without it, continuing a turn that has a pending code-exec tool use 400s:
  // "container_id is required when there are pending tool uses generated by
  // code execution with tools."
  let containerFromWire: string | undefined;
  stream.on("streamEvent", (event) => {
    const e = event as {
      type?: string;
      container?: { id?: string };
      message?: { container?: { id?: string } };
      delta?: { container?: { id?: string } };
    };
    containerFromWire =
      e.message?.container?.id ?? e.delta?.container?.id ?? e.container?.id ?? containerFromWire;
  });
  // TEMPORARY diagnostic tap (env-gated): dump message-level wire events so we
  // can see fields the SDK's stream accumulator drops (e.g. `container` on
  // message_delta). No-op unless FACTORY_DIAG_STREAM=1.
  if (process.env.FACTORY_DIAG_STREAM === "1") {
    stream.on("streamEvent", (event) => {
      const t = (event as { type: string }).type;
      if (t === "message_start" || t === "message_delta" || t === "message_stop") {
        console.error(`[FACTORY_DIAG_STREAM] ${JSON.stringify(event).slice(0, 1500)}`);
      } else if (t === "content_block_start") {
        const cb = (event as { content_block?: { type?: string; name?: string; caller?: unknown } }).content_block;
        console.error(
          `[FACTORY_DIAG_STREAM] block ${cb?.type} ${cb?.name ?? ""} caller=${JSON.stringify(cb?.caller ?? null)}`,
        );
      }
    });
  }
  if (opts.onText) stream.on("text", (delta: string) => opts.onText!(delta));
  if (opts.onToolNote) {
    stream.on("streamEvent", (event) => {
      if (event.type === "content_block_start") {
        const t = event.content_block.type;
        if (t === "server_tool_use") opts.onToolNote!("searching the web…");
        else if (t === "web_search_tool_result") opts.onToolNote!("reading search results…");
      }
    });
  }
  const msg = await stream.finalMessage();
  if (containerFromWire && !msg.container) {
    (msg as { container?: unknown }).container = { id: containerFromWire, expires_at: "" };
  }
  return msg;
}

export async function call(
  client: Anthropic,
  p: CallParams,
  opts: CallOptions = {},
): Promise<Anthropic.Message> {
  const base = buildParams(p);
  let msg = await streamOnce(client, base, opts);
  opts.onUsage?.(p.model, msg.usage as Usage);
  // The container id (code-execution-backed server tools, e.g. web_search) may
  // arrive on an EARLY pause segment and be null on later ones. Remember it,
  // pass it on every pause resume, and surface it on the returned message so
  // callers that continue this turn (client tool_result rounds) can echo it —
  // without it the API 400s: "container_id is required when there are pending
  // tool uses generated by code execution with tools."
  let containerId: string | undefined = msg.container?.id ?? p.container ?? undefined;
  const maxResumes = opts.maxPauseResumes ?? 3;
  for (let i = 0; i < maxResumes && msg.stop_reason === "pause_turn"; i++) {
    const messages = [...(p.messages as Anthropic.MessageParam[]), { role: "assistant" as const, content: msg.content }];
    msg = await streamOnce(client, { ...base, messages, ...(containerId ? { container: containerId } : {}) }, opts);
    opts.onUsage?.(p.model, msg.usage as Usage);
    containerId = msg.container?.id ?? containerId;
  }
  if (msg.stop_reason === "refusal") {
    throw new Error("The request was declined by the model's safety systems.");
  }
  if (containerId && !msg.container) {
    (msg as { container?: unknown }).container = { id: containerId, expires_at: "" };
  }
  return msg;
}

export function textOf(msg: Anthropic.Message): string {
  return (msg.content || [])
    .filter((b): b is Anthropic.TextBlock => b.type === "text")
    .map((b) => b.text)
    .join("\n");
}

// Matches ASCII control chars (U+0000–U+001F) that are illegal inside a JSON
// string. Built via RegExp() so no literal control bytes live in this source.
const CONTROL_CHARS = new RegExp("[\\u0000-\\u001F]", "g");

// Tolerant JSON extraction (mirrors the prototype's parseJSON).
export function parseJSONLoose<T = unknown>(text: string): T {
  try {
    return JSON.parse(text) as T;
  } catch {
    /* fall through to bracket extraction */
  }
  const start = text.indexOf("{");
  const end = text.lastIndexOf("}");
  if (start >= 0 && end > start) {
    const slice = text.slice(start, end + 1);
    try {
      return JSON.parse(slice) as T;
    } catch {
      /* fall through */
    }
    // Last resort: drop stray control characters (a raw newline/tab inside a
    // string is invalid JSON and the most common cause of a parse failure) and
    // retry. CONTROL_CHARS is built without literal control bytes in source.
    try {
      return JSON.parse(slice.replace(CONTROL_CHARS, " ")) as T;
    } catch {
      /* fall through */
    }
  }
  throw new Error("Could not parse JSON from model response");
}
