import { type MissionDefinition, type MissionType } from "./types";

export const MISSION_CATALOGUE: MissionDefinition[] = [
  {
    priority: 1,
    type: "viability_tribunal",
    slug: "viability-tribunal",
    purpose: "challenge",
    name: "Viability Tribunal",
    shortName: "Viability",
    question: "Can this campaign actually win?",
    pattern: "Tribunal",
    availability: "runnable",
    team: [
      { key: "advocate", name: "Campaign Advocate" },
      { key: "falsifier", name: "Campaign Falsifier" },
      { key: "formal-route", name: "Formal Route Examiner" },
      { key: "capacity", name: "Capacity Examiner" },
      { key: "chair", name: "Tribunal Chair" },
    ],
    tools: ["Immutable campaign snapshot", "Campaign evidence register", "Independent examination", "Disagreement-preserving synthesis"],
    artefact: "A verdict with agreements, disagreements, failure conditions, evidence and recommended changes.",
    humanDecision: "Decide whether the verdict is useful, needs local knowledge or should be rejected.",
    reviewActions: ["Tribunal reviewed", "Needs local knowledge", "Reject verdict"],
    boundary: "Cannot alter the campaign objective, strategy, tactics or documents.",
    cadence: "one_off",
  },
  {
    priority: 2,
    type: "evidence_audit",
    slug: "whole-campaign-evidence-audit",
    purpose: "investigate",
    name: "Whole-Campaign Evidence Audit",
    shortName: "Evidence audit",
    question: "Which campaign claims remain usable, stale, conflicted or unsupported?",
    pattern: "Parallel team",
    availability: "runnable",
    team: [
      { key: "claim-inventory", name: "Claim Inventory Agent" },
      { key: "source-rechecker", name: "Source Rechecker" },
      { key: "freshness", name: "Freshness Checker" },
      { key: "conflicts", name: "Conflict Finder" },
      { key: "chair", name: "Evidence Chair" },
    ],
    tools: ["Every source claim and lint item", "Official web research", "Dated citations", "24-claim recheck cap"],
    artefact: "A labelled evidence ledger, explicit gaps and a prioritised verification queue.",
    humanDecision: "Review the audit, request local verification or reject it.",
    reviewActions: ["Audit reviewed", "Needs local verification", "Reject audit"],
    boundary: "No evidence-register label, claim or source is automatically changed.",
    cadence: "one_off",
  },
  {
    priority: 3,
    type: "decision_route_audit",
    slug: "decision-route-meetings-audit",
    purpose: "investigate",
    name: "Decision Route & Meetings Audit",
    shortName: "Decision route",
    question: "Who formally decides, through which route, and when can the campaign intervene?",
    pattern: "Parallel team",
    availability: "runnable",
    team: [
      { key: "authority", name: "Authority and Procedure Researcher" },
      { key: "council", name: "Council Meetings and Minutes Researcher" },
      { key: "parliament", name: "Parliament and Public-Body Researcher" },
      { key: "timetable", name: "Timetable and Consultation Researcher" },
      { key: "chair", name: "Route Reconciler" },
    ],
    tools: ["UK Parliament supported APIs", "Detected ModernGov services", "Official-domain web research", "12-month and 90-day date windows"],
    artefact: "A verified route, intervention points, meetings, minutes, deadlines, conflicts and provider coverage ledger.",
    humanDecision: "Review the formal route, request local verification or reject it.",
    reviewActions: ["Route reviewed", "Needs local verification", "Reject route"],
    boundary: "Only primary Parliament, council or public-body records may verify the formal route. Unsupported coverage stays incomplete.",
    cadence: "one_off",
  },
  {
    priority: 4,
    type: "precedent_review",
    slug: "campaign-precedent-review",
    purpose: "investigate",
    name: "Campaign Precedent Review",
    shortName: "Precedents",
    question: "What did comparable campaigns teach, and where does the comparison break?",
    pattern: "Parallel team",
    availability: "runnable",
    team: [
      { key: "issue", name: "Issue Similarity Researcher" },
      { key: "institution", name: "Institution Comparator" },
      { key: "pressure", name: "Pressure and Tactics Researcher" },
      { key: "failure", name: "Failure and Unintended-Effects Researcher" },
      { key: "chair", name: "Transferability Chair" },
    ],
    tools: ["Open web research", "Source-quality checks", "Cross-case comparison", "Causal-claim guardrails"],
    artefact: "Three to six sourced precedents with outcomes, differences, mechanisms, failures and transfer limits.",
    humanDecision: "Use the review as planning input, add local knowledge or reject it.",
    reviewActions: ["Use as planning input", "Needs local knowledge", "Reject review"],
    boundary: "Causal claims remain inference unless the cited source directly evidences the causal link.",
    cadence: "one_off",
  },
  {
    priority: 5,
    slug: "decision-route-watcher",
    purpose: "watch",
    name: "Decision-Route Watcher",
    shortName: "Route watcher",
    question: "What public meeting, minute, consultation or parliamentary event changes this campaign?",
    pattern: "Persistent loop",
    availability: "next",
    team: [{ key: "watcher", name: "Verified Source Watcher" }],
    tools: ["Verified source list from the route audit", "Durable scheduling", "Change detection"],
    artefact: "A sourced change brief for human review.",
    humanDecision: "Acknowledge, investigate or update the campaign manually.",
    reviewActions: ["Reviewed", "Investigate", "Dismiss"],
    boundary: "Cannot silently change the campaign or contact anyone.",
    cadence: "persistent",
  },
  {
    priority: 6,
    slug: "campaign-change-response",
    purpose: "prepare",
    name: "Campaign Change Response",
    shortName: "Change response",
    question: "What should change when new public evidence alters the campaign?",
    pattern: "Response loop",
    availability: "next",
    team: [{ key: "response", name: "Change Response Team" }],
    tools: ["Approved change brief", "Campaign dependency map"],
    artefact: "A proposed change set with evidence, dependencies and retained disagreements.",
    humanDecision: "Approve each proposed change individually.",
    reviewActions: ["Reviewed", "Needs work", "Reject"],
    boundary: "Cannot update the campaign or publish a response without approval.",
    cadence: "one_off",
  },
  {
    priority: 7,
    slug: "decision-maker-meeting-pack",
    purpose: "prepare",
    name: "Decision-Maker Meeting Pack",
    shortName: "Meeting pack",
    question: "What does the team need for a specific, evidence-led meeting?",
    pattern: "Parallel team",
    availability: "next",
    team: [{ key: "pack", name: "Meeting Pack Team" }],
    tools: ["Verified route", "Approved campaign case"],
    artefact: "A meeting brief, agenda, talking points, questions and evidence annex.",
    humanDecision: "Edit and approve the pack before the meeting.",
    reviewActions: ["Approved", "Needs edits", "Reject"],
    boundary: "Cannot request, attend or follow up on a meeting.",
    cadence: "one_off",
  },
  {
    priority: 8,
    slug: "minimum-viable-win",
    purpose: "challenge",
    name: "Minimum Viable Win",
    shortName: "Minimum win",
    question: "Is there a smaller meaningful decision we could win first?",
    pattern: "Parallel team",
    availability: "later",
    team: [{ key: "minimum-win", name: "Minimum Win Team" }],
    tools: ["Decision route", "Campaign constraints"],
    artefact: "Ranked stepping-stone wins, or a finding that none is credible.",
    humanDecision: "Keep the objective or investigate a stepping-stone win.",
    reviewActions: ["Reviewed", "Investigate", "Reject"],
    boundary: "Cannot replace the approved objective or recommend a token win.",
    cadence: "one_off",
  },
  {
    priority: 9,
    slug: "evidence-freshness-watch",
    purpose: "watch",
    name: "Evidence Freshness Watch",
    shortName: "Freshness watch",
    question: "Which source-backed claims may no longer be current?",
    pattern: "Persistent loop",
    availability: "later",
    team: [{ key: "freshness-watch", name: "Evidence Watch Team" }],
    tools: ["Verified source register", "Version comparison"],
    artefact: "A freshness report with changed, missing and superseded sources.",
    humanDecision: "Re-verify affected campaign claims.",
    reviewActions: ["Reviewed", "Verify", "Dismiss"],
    boundary: "A missing page is not proof that the underlying fact changed.",
    cadence: "persistent",
  },
  {
    priority: 10,
    slug: "institutional-response-simulation",
    purpose: "challenge",
    name: "Institutional Response Simulation",
    shortName: "Response simulation",
    question: "How might the institution respond to this strategy?",
    pattern: "Tribunal",
    availability: "later",
    team: [{ key: "simulation", name: "Response Simulation Team" }],
    tools: ["Documented institutional options", "Scenario testing"],
    artefact: "A branching response tree with warning signs, vulnerabilities and contingencies.",
    humanDecision: "Choose which scenarios deserve contingency planning.",
    reviewActions: ["Reviewed", "Needs evidence", "Reject"],
    boundary: "Cannot present scenarios as the intentions or positions of named people.",
    cadence: "one_off",
  },
  {
    priority: 11,
    slug: "next-move-operations-pack",
    purpose: "prepare",
    name: "Next-Move Operations Pack",
    shortName: "Operations pack",
    question: "What should this campaign do during its next bounded phase?",
    pattern: "Parallel team",
    availability: "later",
    team: [{ key: "operations", name: "Operations Pack Team" }],
    tools: ["Approved strategy", "Capacity constraints"],
    artefact: "A short phase plan with owners, dependencies, approvals and stop conditions.",
    humanDecision: "Assign real owners and approve the phase.",
    reviewActions: ["Approved", "Needs edits", "Reject"],
    boundary: "Cannot assign work to people or initiate external activity.",
    cadence: "one_off",
  },
  {
    priority: 12,
    slug: "local-public-narrative-watch",
    purpose: "watch",
    name: "Local Public Narrative Watch",
    shortName: "Narrative watch",
    question: "How is the issue appearing in public local debate?",
    pattern: "Persistent loop",
    availability: "later",
    team: [{ key: "narrative-watch", name: "Public Narrative Watch Team" }],
    tools: ["Public local sources", "Theme comparison"],
    artefact: "A sourced briefing on public narratives, changes and unanswered claims.",
    humanDecision: "Decide whether the campaign narrative needs review.",
    reviewActions: ["Reviewed", "Investigate", "Dismiss"],
    boundary: "Uses public material only and cannot infer private opinion or profile individuals.",
    cadence: "persistent",
  },
];

export const RUNNABLE_MISSIONS = MISSION_CATALOGUE.filter(
  (mission): mission is MissionDefinition & { type: MissionType } => mission.availability === "runnable" && Boolean(mission.type),
);

export const FUTURE_MISSIONS = MISSION_CATALOGUE.filter((mission) => mission.availability !== "runnable");

export function getMissionByType(type: MissionType): MissionDefinition & { type: MissionType } {
  const mission = RUNNABLE_MISSIONS.find((candidate) => candidate.type === type);
  if (!mission) throw new Error(`Unknown mission type: ${type}`);
  return mission;
}

export function getMissionBySlug(slug: string): (MissionDefinition & { type: MissionType }) | undefined {
  return RUNNABLE_MISSIONS.find((mission) => mission.slug === slug);
}

export function availabilityLabel(value: MissionDefinition["availability"]): string {
  if (value === "runnable") return "Runnable";
  if (value === "next") return "Next";
  return "Later";
}
