import { type MissionDefinition, type MissionPurpose } from "./types";

export const PURPOSES: { id: MissionPurpose; label: string; description: string }[] = [
  { id: "challenge", label: "Challenge", description: "Test whether the campaign can work before it consumes scarce time." },
  { id: "investigate", label: "Investigate", description: "Close evidence gaps and examine the formal route to the decision." },
  { id: "watch", label: "Watch", description: "Keep public evidence and decision points under review after the plan is written." },
  { id: "prepare", label: "Prepare", description: "Turn the approved strategy into a bounded operational response." },
];

export const MISSION_CATALOGUE: MissionDefinition[] = [
  {
    slug: "viability-tribunal",
    purpose: "challenge",
    name: "Viability Tribunal",
    question: "Can this campaign actually win?",
    pattern: "Tribunal",
    availability: "available",
    team: ["Campaign Advocate", "Campaign Falsifier", "Formal Route Examiner", "Capacity Examiner", "Tribunal Chair"],
    artefact: "A verdict with agreements, disagreements, failure conditions, evidence and recommended changes.",
    humanDecision: "Accept the review, reject it, or flag where local knowledge is still required.",
    boundary: "Cannot alter the campaign objective, strategy, tactics or documents.",
    cadence: "one_off",
  },
  {
    slug: "institutional-response-simulation",
    purpose: "challenge",
    name: "Institutional Response Simulation",
    question: "How might the institution respond to this strategy?",
    pattern: "Tribunal",
    availability: "future",
    team: ["Formal Options Analyst", "Institutional Incentives Analyst", "Counterargument Researcher", "Procedural Response Analyst", "Scenario Reviewer"],
    artefact: "A branching response tree with warning signs, vulnerabilities and contingencies.",
    humanDecision: "Choose which scenarios deserve contingency planning.",
    boundary: "Cannot present scenarios as the intentions or positions of named people.",
    cadence: "one_off",
  },
  {
    slug: "minimum-viable-win",
    purpose: "challenge",
    name: "Minimum Viable Win",
    question: "Is there a smaller meaningful decision we could win first?",
    pattern: "Parallel Team",
    availability: "future",
    team: ["Decision-Route Analyst", "Policy Alternatives Analyst", "Resource Analyst", "Coalition Analyst", "Win Evaluator"],
    artefact: "Ranked stepping-stone wins, or a finding that no credible smaller win exists.",
    humanDecision: "Keep the objective or investigate a stepping-stone win.",
    boundary: "Cannot replace the approved objective or recommend a token win.",
    cadence: "one_off",
  },
  {
    slug: "campaign-precedent-review",
    purpose: "investigate",
    name: "Campaign Precedent Review",
    question: "What did similar campaigns teach, and where does the comparison break?",
    pattern: "Parallel Team",
    availability: "future",
    team: ["Issue Comparator", "Institution Comparator", "Pressure Comparator", "Failure Researcher", "Transferability Evaluator"],
    artefact: "A comparative precedent dossier with successes, failures and limits to transfer.",
    humanDecision: "Select precedents for deeper local discussion.",
    boundary: "Cannot claim that a tactic caused an outcome without supporting evidence.",
    cadence: "one_off",
  },
  {
    slug: "formal-decision-route-audit",
    purpose: "investigate",
    name: "Formal Decision-Route Audit",
    question: "Is the documented route to the decision correct and current?",
    pattern: "Parallel Team",
    availability: "up_next",
    team: ["Authority Researcher", "Committee Researcher", "Minutes Researcher", "Timetable Researcher", "Route Reconciler"],
    artefact: "A verified route map with authorities, committees, dates, conflicts and gaps.",
    humanDecision: "Confirm the route or commission local verification.",
    boundary: "Covers documented public processes, not private influence or inferred relationships.",
    cadence: "one_off",
  },
  {
    slug: "whole-campaign-evidence-audit",
    purpose: "investigate",
    name: "Whole-Campaign Evidence Audit",
    question: "Which claims are strong enough to use, stale, conflicted or unsupported?",
    pattern: "Parallel Team",
    availability: "up_next",
    team: ["Claim Extractor", "Source Checker", "Conflict Resolver", "Freshness Reviewer", "Evidence Chair"],
    artefact: "A campaign-wide evidence ledger and prioritised verification queue.",
    humanDecision: "Approve, correct or remove claims before use.",
    boundary: "Cannot invent a source or convert strategic inference into verified fact.",
    cadence: "one_off",
  },
  {
    slug: "decision-route-watcher",
    purpose: "watch",
    name: "Decision-Route Watcher",
    question: "What public meeting, minute, consultation or parliamentary event changes this campaign?",
    pattern: "Persistent Loop",
    availability: "up_next",
    team: ["Source Scheduler", "Meeting Matcher", "Change Detector", "Relevance Reviewer", "Briefing Writer"],
    artefact: "A sourced change brief and suggested questions for human review.",
    humanDecision: "Acknowledge, investigate or update the campaign manually.",
    boundary: "Cannot silently change the campaign or contact anyone.",
    cadence: "persistent",
  },
  {
    slug: "evidence-freshness-watch",
    purpose: "watch",
    name: "Evidence Freshness Watch",
    question: "Which source-backed claims may no longer be current?",
    pattern: "Persistent Loop",
    availability: "future",
    team: ["Source Scheduler", "Document Fetcher", "Version Comparator", "Claim Reviewer", "Change Summariser"],
    artefact: "A freshness report with changed, missing and superseded sources.",
    humanDecision: "Re-verify affected campaign claims.",
    boundary: "Cannot treat a missing page as proof that the underlying fact changed.",
    cadence: "persistent",
  },
  {
    slug: "local-public-narrative-watch",
    purpose: "watch",
    name: "Local Public Narrative Watch",
    question: "How is the issue appearing in public local debate?",
    pattern: "Persistent Loop",
    availability: "future",
    team: ["Local Media Monitor", "Public Statement Monitor", "Theme Extractor", "Evidence Reviewer", "Narrative Briefing Writer"],
    artefact: "A sourced briefing on public narratives, changes and unanswered claims.",
    humanDecision: "Decide whether the campaign narrative needs review.",
    boundary: "Uses public material only and cannot infer private opinion or profile individuals.",
    cadence: "persistent",
  },
  {
    slug: "decision-maker-meeting-pack",
    purpose: "prepare",
    name: "Decision-Maker Meeting Pack",
    question: "What does the team need for a specific, evidence-led meeting?",
    pattern: "Parallel Team",
    availability: "future",
    team: ["Briefing Researcher", "Argument Writer", "Objection Analyst", "Question Writer", "Pack Reviewer"],
    artefact: "A meeting brief, agenda, talking points, questions and evidence annex.",
    humanDecision: "Edit and approve the pack before the meeting.",
    boundary: "Cannot request, attend or follow up on a meeting.",
    cadence: "one_off",
  },
  {
    slug: "campaign-change-response",
    purpose: "prepare",
    name: "Campaign Change Response",
    question: "What should change when new public evidence alters the campaign?",
    pattern: "Response Loop",
    availability: "up_next",
    team: ["Change Assessor", "Strategy Impact Analyst", "Tactics Impact Analyst", "Resource Reviser", "Response Chair"],
    artefact: "A proposed change set with evidence, dependencies and retained disagreements.",
    humanDecision: "Approve each proposed change individually.",
    boundary: "Cannot update the campaign or publish a response without approval.",
    cadence: "one_off",
  },
  {
    slug: "next-move-operations-pack",
    purpose: "prepare",
    name: "Next-Move Operations Pack",
    question: "What should this campaign do during its next bounded phase?",
    pattern: "Parallel Team",
    availability: "future",
    team: ["Sequence Planner", "Volunteer Capacity Analyst", "Contact Planner", "Event Planner", "Readiness Reviewer"],
    artefact: "A short phase plan with owners, dependencies, approvals and stop conditions.",
    humanDecision: "Assign real owners and approve the phase.",
    boundary: "Cannot assign work to people or initiate external activity.",
    cadence: "one_off",
  },
];

export const VIABILITY_TRIBUNAL = MISSION_CATALOGUE[0];

export function availabilityLabel(value: MissionDefinition["availability"]): string {
  if (value === "available") return "Available now";
  if (value === "up_next") return "Up next";
  return "Future mission concept";
}
